version: 2
updates:
- package-ecosystem: cargo
  # Look for `Cargo.toml` and `Cargo.lock` in the root directory
  directory: "/social-image"
  # Check for updates every Monday
  schedule:
    interval: monthly
  open-pull-requests-limit: 5
