[package]
name = "social-image"
version = "0.1.0"
edition = "2021"
description = "Generate social images using SVG templates"
repository = "https://github.com/clord/social-image"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"
